#include "codegen.h"
#include "type_checker.h"
#include <sstream>
#include <stdexcept>
#include <unordered_set>
#include <unordered_map>
#include <cstdint>
#include <cinttypes>

namespace brick {

class Codegen {
public:
    Codegen(const PackageTable& packages)
        : packages(packages), indent_level(0), current_line(-1) {}

    CodegenResult generate(const std::vector<std::unique_ptr<ProgramNode>>& asts) {
        CodegenResult result;

        try {
            TypeChecker tc(packages);
            auto tc_errors = tc.check(asts);
            if (!tc_errors.empty()) {
                result.errors = tc_errors;
                result.success = false;
                return result;
            }

            collect_structs(asts);

            // First pass: process includes, links, and collect extern funcs
            // Primeira passada: processa includes, links e coleta funcs externas
            for (const auto& ast : asts) {
                for (const auto& decl : ast->declarations) {
                    switch (decl->type) {
            case ASTNodeType::INCLUDE_DECL: {
                auto* inc = static_cast<IncludeDecl*>(decl.get());
                out << "#include <" << inc->header << ">\n";
                if (!inc->link_lib.empty())
                    result.link_flags.push_back(inc->link_lib);
                break;
            }
            case ASTNodeType::LINK_DECL: {
                auto* ld = static_cast<LinkDecl*>(decl.get());
                result.link_flags.push_back(ld->lib);
                break;
            }
            case ASTNodeType::FUNC_DECL: {
                auto* fd = static_cast<FuncDecl*>(decl.get());
                if (fd->is_extern)
                    extern_funcs[fd->name] = fd;
                break;
            }
            case ASTNodeType::MACRO_DECL:
            case ASTNodeType::BUILD_BLOCK:
            case ASTNodeType::EMIT_STMT:
            case ASTNodeType::MACRO_CALL:
            case ASTNodeType::INTERPOLATE:
            case ASTNodeType::VALUE_PLACEHOLDER:
                // These should be resolved before codegen — skip silently
                // Estes devem ser resolvidos antes do codegen — pula silenciosamente
                break;
            default: break;
                    }
                }
            }
            out << "\n";

            out << "/* Generated by Brick */\n";
            out << "#include <stdint.h>\n";
            out << "#include <inttypes.h>\n";
            out << "#include <stddef.h>\n";
            out << "#include <string.h>\n";
            out << "#include <stdio.h>\n";
            out << "#include <stdlib.h>\n";
            out << "#include \"block_memory.h\"\n";
            out << "#include \"io.h\"\n";
            out << "#include \"pool_allocator.h\"\n\n";

            for (const auto& ast : asts) {
                for (const auto& decl : ast->declarations) {
                    if (decl->type == ASTNodeType::STRUCT_DECL) {
                        auto* sd = static_cast<StructDecl*>(decl.get());
                        out << "typedef struct " << sd->name << " " << sd->name << ";\n";
                    }
                }
            }
            out << "\n";

            // Extern prototypes NOT emitted — C headers provide declarations
            // Prototipos extern NAO emitidos — headers C fornecem as declaracoes

            for (const auto& ast : asts) {
                for (const auto& decl : ast->declarations) {
                    if (decl->type == ASTNodeType::STRUCT_DECL) {
                        gen_struct(static_cast<StructDecl*>(decl.get()));
                    }
                }
            }

            out << "// Block context variables\n";
            gen_block_vars(asts);
            gen_block_init(asts);
            out << "\n";

            for (const auto& ast : asts) {
                for (const auto& decl : ast->declarations) {
                    if (decl->type == ASTNodeType::STRUCT_DECL) {
                        auto* sd = static_cast<StructDecl*>(decl.get());
                        for (const auto& method : sd->methods) {
                            if (method->type == ASTNodeType::FUNC_DECL) {
                                gen_function(static_cast<FuncDecl*>(method.get()), sd->name);
                            }
                        }
                    }
                    if (decl->type == ASTNodeType::FUNC_DECL) {
                        auto* fd = static_cast<FuncDecl*>(decl.get());
                        if (!fd->is_extern)
                            gen_function(fd, "");
                    }
                }
            }

            result.c_code = out.str();
            result.success = true;

        } catch (const std::exception& e) {
            result.errors.push_back(e.what());
        }

        return result;
    }

private:
    const PackageTable& packages;
    std::ostringstream out;
    int indent_level;
    int current_line;
    std::string current_file;

    std::unordered_map<std::string, StructDecl*> struct_map;
    std::unordered_map<std::string, FuncDecl*> extern_funcs;
    std::unordered_set<std::string> declared_vars;
    std::unordered_map<std::string, bool> pointer_vars;
    bool has_blocks_ = false;
    bool has_pool_ = false;
    std::unordered_set<std::string> pool_blocks_;
    int scope_depth = 0;

    std::string current_struct_name;
    std::unordered_set<std::string> current_struct_fields;

    void indent() {
        for (int i = 0; i < indent_level; i++) out << "    ";
    }

    void emit_line(SourceLocation loc) {
        if (loc.line != current_line || loc.file != current_file) {
            if (!loc.file.empty() && loc.file != "<input>") {
                out << "#line " << loc.line << " \"" << loc.file << "\"\n";
            }
            current_line = loc.line;
            current_file = loc.file;
        }
    }

    std::string mangle_name(const std::string& struct_name, const std::string& func_name) {
        return struct_name + "_" + func_name;
    }

    void collect_structs(const std::vector<std::unique_ptr<ProgramNode>>& asts) {
        for (const auto& ast : asts) {
            for (const auto& decl : ast->declarations) {
                if (decl->type == ASTNodeType::STRUCT_DECL) {
                    auto* sd = static_cast<StructDecl*>(decl.get());
                    struct_map[sd->name] = sd;
                }
            }
        }
    }

    static int64_t parse_block_size(int64_t size, const std::string& unit) {
        if (unit == "KB" || unit == "K") return size * 1024;
        if (unit == "MB" || unit == "M") return size * 1024 * 1024;
        if (unit == "GB" || unit == "G") return size * 1024 * 1024 * 1024;
        return size;
    }

    // Check if a type is a float type (f32/f32/float/double)
    // Verifica se um tipo e float (f32/f32/float/double)
    bool is_float_type_for_simd(const std::string& t) {
        return t == "f32" || t == "f64" || t == "float" || t == "double";
    }

    // Check if a type is a float array like "f32[4]"
    // Verifica se um tipo e array de float como "f32[4]"
    bool is_float_array(const std::string& t) {
        auto bracket = t.find('[');
        if (bracket == std::string::npos) return false;
        return is_float_type_for_simd(t.substr(0, bracket));
    }

    // Get SIMD alignment for a float type: f32→16, f64→16, f32[4]→16, f64[4]→32
    // Obtem alinhamento SIMD para um tipo float: f32→16, f64→16, f32[4]→16, f64[4]→32
    int get_simd_alignment(const std::string& type_name) {
        auto bracket = type_name.find('[');
        if (bracket != std::string::npos) {
            std::string base = type_name.substr(0, bracket);
            std::string count_str = type_name.substr(bracket + 1, type_name.find(']') - bracket - 1);
            int count = std::stoi(count_str);
            if (base == "f64" || base == "double") return count >= 2 ? 32 : 16;
            return count >= 4 ? 16 : 8;
        }
        if (type_name == "f64" || type_name == "double") return 16;
        return 8;
    }

    // Estimate byte size of a Brick type for pool allocator decision
    // Estima tamanho em bytes de um tipo Brick para decisao do pool
    int type_size_estimate(const std::string& type_name) {
        std::unordered_set<std::string> visited;
        return type_size_estimate_impl(type_name, visited);
    }

    int type_size_estimate_impl(const std::string& type_name, std::unordered_set<std::string>& visited) {
        // Array type: base_type[count]
        // Tipo array: base_type[count]
        auto bracket = type_name.find('[');
        if (bracket != std::string::npos) {
            std::string base = type_name.substr(0, bracket);
            std::string count_str = type_name.substr(bracket + 1, type_name.find(']') - bracket - 1);
            int count = std::stoi(count_str);
            return type_size_estimate_impl(base, visited) * count;
        }
        // Pointer type: *T
        if (!type_name.empty() && type_name[0] == '*') {
            return 8; // pointer is 8 bytes on 64-bit
        }
        std::string n = normalize_type_name(type_name);
        if (n == "u8" || n == "i8" || n == "bool" || n == "char") return 1;
        if (n == "u16" || n == "i16") return 2;
        if (n == "u32" || n == "i32" || n == "f32") return 4;
        if (n == "u64" || n == "i64" || n == "f64" || n == "usize" || n == "isize") return 8;
        if (n == "String") return 16; // BrickString { char*, size_t }
        // Struct: sum of field sizes
        if (struct_map.count(n)) {
            if (visited.count(n)) return 64; // circular, cap at threshold
            visited.insert(n);
            int total = 0;
            auto* sd = struct_map[n];
            for (auto& f : sd->fields) {
                if (f->type == ASTNodeType::FIELD_DECL) {
                    auto* fd = static_cast<FieldDecl*>(f.get());
                    total += type_size_estimate_impl(fd->type_name, visited);
                }
            }
            return total;
        }
        return 64; // unknown, assume threshold
    }

    static constexpr int POOL_SIZE_THRESHOLD = 64;

    // Decide if a type should use the pool allocator
    // Decide se um tipo deve usar o pool allocator
    bool should_use_pool(const std::string& type_name) {
        if (type_name.empty()) return false;
        return type_size_estimate(type_name) <= POOL_SIZE_THRESHOLD;
    }

    void gen_struct(StructDecl* sd) {
        emit_line(sd->location);
        indent(); out << "typedef struct " << sd->name << " {\n";
        indent_level++;

        if (!sd->extends.empty()) {
            indent(); out << sd->extends << " base;\n";
        }

        for (const auto& field : sd->fields) {
            if (field->type == ASTNodeType::FIELD_DECL) {
                auto* fd = static_cast<FieldDecl*>(field.get());
                // [OPTIMIZATION] SIMD alignment for float types
                // Add alignment attribute to float/f64 fields and float arrays
                // Adiciona atributo de alinhamento para campos float/f64 e arrays float
                if (is_float_type_for_simd(fd->type_name) || is_float_array(fd->type_name)) {
                    indent(); out << "__attribute__((aligned("
                                  << get_simd_alignment(fd->type_name) << ")))\n";
                }
                indent(); out << map_type(fd->type_name) << " " << fd->name << ";\n";
            }
        }

        indent_level--;
        indent(); out << "} " << sd->name << ";\n\n";
    }

    void gen_block_vars(const std::vector<std::unique_ptr<ProgramNode>>& asts) {
        for (const auto& ast : asts) {
            for (const auto& decl : ast->declarations) {
                if (decl->type == ASTNodeType::BLOCK_DECL) {
                    auto* bd = static_cast<BlockDecl*>(decl.get());
                    indent();
                    out << "BlockCtx* " << bd->name << ";\n";
                    // Every block gets a pool for small allocations
                    // Todo bloco ganha um pool para alocacoes pequenas
                    indent();
                    out << "PoolAllocator* __pool_" << bd->name << ";\n";
                    pool_blocks_.insert(bd->name);
                    has_pool_ = true;
                }
            }
        }
        indent(); out << "BlockCtx* _current_block = NULL;\n";
    }

    void gen_block_init(const std::vector<std::unique_ptr<ProgramNode>>& asts) {
        if (asts.empty()) return;
        has_blocks_ = false;
        for (const auto& ast : asts) {
            for (const auto& decl : ast->declarations) {
                if (decl->type == ASTNodeType::BLOCK_DECL) { has_blocks_ = true; break; }
            }
        }
        if (!has_blocks_) return;

        indent(); out << "void __brick_init() {\n";
        indent_level++;
        for (const auto& ast : asts) {
            for (const auto& decl : ast->declarations) {
                if (decl->type == ASTNodeType::BLOCK_DECL) {
                    auto* bd = static_cast<BlockDecl*>(decl.get());
                    int64_t bytes = parse_block_size(bd->size, bd->unit);
                    indent();
                    out << bd->name << " = block_create_bytes(" << bytes << ");\n";
                    indent();
                    out << "block_register(" << bd->name << ", \"" << bd->name << "\");\n";
                    // Create pool for small allocations in this block
                    // Cria pool para alocacoes pequenas neste bloco
                    indent();
                    out << "__pool_" << bd->name << " = pool_create();\n";
                    indent();
                    out << "pool_add_slot(__pool_" << bd->name << ", 64, 4096);\n";
                }
            }
        }
        // Initialize _current_block to first declared block
        // Inicializa _current_block para o primeiro bloco declarado
        for (const auto& ast : asts) {
            for (const auto& decl : ast->declarations) {
                if (decl->type == ASTNodeType::BLOCK_DECL) {
                    auto* bd = static_cast<BlockDecl*>(decl.get());
                    indent(); out << "_current_block = " << bd->name << ";\n";
                    goto done_current_block;
                }
            }
        }
        done_current_block:

        indent(); out << "block_shm_export();\n";

        // Set up TLS for the main thread
        // Configura TLS para a thread principal
        indent(); out << "block_set_tls(_current_block);\n";

        indent_level--;
        indent(); out << "}\n\n";

        // Cleanup: destroy pools
        // Limpeza: destroi os pools
        indent(); out << "void __brick_cleanup() {\n";
        indent_level++;
        for (const auto& name : pool_blocks_) {
            indent(); out << "pool_destroy(__pool_" << name << ");\n";
            indent(); out << "__pool_" << name << " = NULL;\n";
        }
        indent_level--;
        indent(); out << "}\n\n";
    }

    void gen_extern_prototype(FuncDecl* fd) {
        std::string ret_type = map_type(
            fd->return_type.empty() ? "void" : fd->return_type);
        indent();
        out << "extern " << ret_type << " " << fd->name << "(";

        for (size_t i = 0; i < fd->params.size(); i++) {
            auto* pd = static_cast<ParamDecl*>(fd->params[i].get());
            out << map_type(pd->type_name);
            if (i + 1 < fd->params.size()) out << ", ";
        }
        out << ");\n";
    }

    void gen_function(FuncDecl* fd, const std::string& struct_prefix) {
        emit_line(fd->location);
        std::string func_name = struct_prefix.empty()
            ? fd->name
            : mangle_name(struct_prefix, fd->name);

        // main() must return int in C
        // main() deve retornar int em C
        bool is_main = (func_name == "main");
        std::string ret_type = is_main ? "int" : map_type(
            fd->return_type.empty() ? "void" : fd->return_type);

        // [OPTIMIZATION] Inline hints for gcc
        // Add __attribute__((always_inline)) to non-main, non-extern functions
        // Adiciona __attribute__((always_inline)) para funcoes que nao sao main nem extern
        if (!is_main && !fd->is_extern) {
            indent(); out << "__attribute__((always_inline))\n";
            indent(); out << "static inline\n";
        }

        indent();
        out << ret_type << " " << func_name << "(";

        if (!struct_prefix.empty()) {
            out << struct_prefix << "* this";
            if (!fd->params.empty()) out << ", ";
        }

        for (size_t i = 0; i < fd->params.size(); i++) {
            auto* pd = static_cast<ParamDecl*>(fd->params[i].get());
            std::string c_type = map_type(pd->type_name);
            // Struct params become pointers (block-allocated semantics)
            // Params de struct viram ponteiros (semantica de alocacao em bloco)
            bool is_struct_param = struct_map.count(pd->type_name) > 0;
            if (is_struct_param) {
                c_type += "*";
                pointer_vars[pd->name] = true;
            }
            out << c_type << " " << pd->name;
            if (i + 1 < fd->params.size()) out << ", ";
        }
        out << ") {\n";

        indent_level++;
        declared_vars.clear();
        scope_depth = 0;

        // Set struct context for field access (this->field)
        // Define contexto de struct para acesso a campos (this->field)
        std::string prev_struct = current_struct_name;
        std::unordered_set<std::string> prev_fields = current_struct_fields;
        current_struct_name = struct_prefix;
        current_struct_fields.clear();
        if (!struct_prefix.empty() && struct_map.count(struct_prefix)) {
            auto* sd = struct_map[struct_prefix];
            // Collect own fields
            // Coleta campos proprios
            for (const auto& f : sd->fields) {
                if (f->type == ASTNodeType::FIELD_DECL) {
                    current_struct_fields.insert(static_cast<FieldDecl*>(f.get())->name);
                }
            }
            // Collect inherited fields
            // Coleta campos herdados
            if (!sd->extends.empty() && struct_map.count(sd->extends)) {
                collect_fields_recursive(sd->extends);
            }
        }

        if (fd->body) {
            if (is_main && has_blocks_) {
                indent(); out << "__brick_init();\n";
            }
            gen_block_stmt(static_cast<BlockStmt*>(fd->body.get()));
        }

        if (is_main) {
            if (has_pool_) {
                indent(); out << "__brick_cleanup();\n";
            }
            indent(); out << "return 0;\n";
        }

        current_struct_name = prev_struct;
        current_struct_fields = prev_fields;

        indent_level--;
        indent(); out << "}\n\n";
    }

    void collect_fields_recursive(const std::string& struct_name) {
        if (!struct_map.count(struct_name)) return;
        auto* sd = struct_map[struct_name];
        for (const auto& f : sd->fields) {
            if (f->type == ASTNodeType::FIELD_DECL) {
                current_struct_fields.insert(static_cast<FieldDecl*>(f.get())->name);
            }
        }
        if (!sd->extends.empty()) {
            collect_fields_recursive(sd->extends);
        }
    }

    void gen_block_stmt(BlockStmt* bs) {
        for (const auto& stmt : bs->statements) {
            gen_statement(stmt.get());
        }
    }

    void gen_statement(ASTNode* node) {
        if (!node) return;
        emit_line(node->location);

        switch (node->type) {
            case ASTNodeType::IF_STMT:
                gen_if_stmt(static_cast<IfStmt*>(node));
                break;
            case ASTNodeType::WHILE_STMT:
                gen_while_stmt(static_cast<WhileStmt*>(node));
                break;
            case ASTNodeType::FOR_STMT:
                gen_for_stmt(static_cast<ForStmt*>(node));
                break;
            case ASTNodeType::RETURN_STMT:
                gen_return_stmt(static_cast<ReturnStmt*>(node));
                break;
            case ASTNodeType::BLOCK_STMT: {
                indent_level++;
                indent(); out << "{\n";
                scope_depth++;
                gen_block_stmt(static_cast<BlockStmt*>(node));
                scope_depth--;
                indent_level--;
                indent(); out << "}\n";
                break;
            }
            case ASTNodeType::BLOCK_DECL: {
                // Already handled as global; if inside function, skip
                // Ja tratado como global; se dentro de funcao, pula
                break;
            }
            case ASTNodeType::BLOCK_SCOPE: {
                auto* bs = static_cast<BlockScope*>(node);
                indent(); out << "{\n";
                indent_level++;
                scope_depth++;
                indent(); out << "BlockCtx* _old" << scope_depth << " = _current_block;\n";
                indent(); out << "_current_block = " << bs->block_name << ";\n";
                for (const auto& s : bs->body) {
                    gen_statement(s.get());
                }
                indent(); out << "_current_block = _old" << scope_depth << ";\n";
                indent_level--;
                scope_depth--;
                indent(); out << "}\n";
                break;
            }
            case ASTNodeType::EXPR_STMT: {
                auto* es = static_cast<ExprStmt*>(node);
                gen_expr_stmt(es->expr.get());
                break;
            }
            default: {
                indent();
                gen_expression(node);
                out << ";\n";
                break;
            }
        }
    }

    bool has_alloc_inline(ASTNode* node) {
        if (!node) return false;
        if (node->type == ASTNodeType::ALLOC_INLINE) return true;
        if (node->type == ASTNodeType::CALL_EXPR) {
            auto* call = static_cast<CallExpr*>(node);
            return has_alloc_inline(call->callee.get());
        }
        return false;
    }

    void gen_expr_stmt(ASTNode* expr) {
        if (expr->type == ASTNodeType::ASSIGNMENT) {
            auto* assign = static_cast<Assignment*>(expr);
            if (assign->target->type == ASTNodeType::IDENT_EXPR) {
                auto* ident = static_cast<IdentExpr*>(assign->target.get());

                    // Struct field assignment inside method: this->field = value
                    // Atribuicao de campo de struct dentro de metodo: this->field = value
                if (!current_struct_name.empty() && current_struct_fields.count(ident->name)) {
                    indent();
                    if (assign->op == TokenType::ASSIGN) {
                        out << "this->" << ident->name << " = ";
                    } else {
                        out << "this->" << ident->name << " " << token_type_to_op(assign->op) << " ";
                    }
                    gen_expression(assign->value.get());
                    out << ";\n";
                    return;
                }

                std::string var_key = std::to_string(scope_depth) + ":" + ident->name;
                if (declared_vars.find(var_key) == declared_vars.end()) {
                    declared_vars.insert(var_key);
                    std::string c_type = map_type(ident->resolved_type.empty()
                        ? "int" : ident->resolved_type);
                    bool is_block_alloc = has_alloc_inline(assign->value.get());

                    // Track pointer variables for . vs -> later
                    // Rastreia variaveis ponteiro para . vs -> depois
                    if (is_block_alloc) {
                        pointer_vars[ident->name] = true;
                    }

                    // Null literal: variable is a pointer initialized to NULL
                    // Literal null: variavel e um ponteiro inicializado como NULL
                    if (assign->value->type == ASTNodeType::NULL_LITERAL) {
                        indent();
                        out << c_type << "* " << ident->name << " = NULL;\n";
                        pointer_vars[ident->name] = true;
                        return;
                    }

                    indent();
                    if (is_block_alloc) {
                        out << c_type << "* " << ident->name;
                    } else {
                        out << c_type << " " << ident->name;
                    }

                    // Handle block alloc + constructor: multi-line
                    // Trata alocacao de bloco + construtor: multi-linha
                    if (is_block_alloc &&
                        assign->value->type == ASTNodeType::ALLOC_INLINE) {
                        auto* ai = static_cast<AllocInline*>(assign->value.get());
                        if (ai->expr->type == ASTNodeType::CALL_EXPR) {
                            auto* call = static_cast<CallExpr*>(ai->expr.get());
                            if (call->callee->type == ASTNodeType::IDENT_EXPR) {
                                auto* callee_ident = static_cast<IdentExpr*>(call->callee.get());
                                if (struct_map.count(callee_ident->name)) {
                                    std::string struct_name = callee_ident->name;
                                    if (should_use_pool(struct_name)) {
                                        out << " = pool_alloc(__pool_" << ai->block_name
                                            << ", sizeof(" << struct_name << "));\n";
                                    } else {
                                        out << " = block_alloc(" << ai->block_name
                                            << ", sizeof(" << struct_name << "));\n";
                                    }
                                    indent();
                                    out << mangle_name(struct_name, struct_name)
                                        << "(" << ident->name;
                                    for (size_t i = 0; i < call->arguments.size(); i++) {
                                        out << ", ";
                                        gen_expression(call->arguments[i].get());
                                    }
                                    out << ");\n";
                                    return;
                                }
                            }
                        }
                        // Generic block alloc
                        // Alocacao generica de bloco
                        if (should_use_pool(ai->expr->resolved_type)) {
                            out << " = pool_alloc(__pool_" << ai->block_name << ", sizeof(";
                        } else {
                            out << " = block_alloc(" << ai->block_name << ", sizeof(";
                        }
                        gen_expression(ai->expr.get());
                        out << "));\n";
                        indent();
                        out << "*" << ident->name << " = ";
                        gen_expression(ai->expr.get());
                        out << ";\n";
                        return;
                    }

                    // Regular variable assignment
                    // Atribuicao de variavel normal
                    out << " = ";
                    gen_expression(assign->value.get());
                    out << ";\n";
                    return;
                }
            }
        }
        indent();
        gen_expression(expr);
        out << ";\n";
    }

    void gen_if_stmt(IfStmt* is) {
        indent(); out << "if (";
        gen_expression(is->condition.get());
        out << ") {\n";
        indent_level++;
        gen_block_stmt(static_cast<BlockStmt*>(is->then_branch.get()));
        indent_level--;
        indent(); out << "}";
        if (is->else_branch) {
            out << " else ";
            if (is->else_branch->type == ASTNodeType::BLOCK_STMT ||
                is->else_branch->type == ASTNodeType::IF_STMT) {
                gen_statement(is->else_branch.get());
            } else {
                out << "{\n";
                indent_level++;
                gen_statement(is->else_branch.get());
                indent_level--;
                indent(); out << "}\n";
            }
        } else {
            out << "\n";
        }
    }

    void gen_while_stmt(WhileStmt* ws) {
        indent(); out << "while (";
        gen_expression(ws->condition.get());
        out << ") {\n";
        indent_level++;
        gen_block_stmt(static_cast<BlockStmt*>(ws->body.get()));
        indent_level--;
        indent(); out << "}\n";
    }

    void gen_for_stmt(ForStmt* fs) {
        indent(); out << "for (";
        if (fs->init) {
            if (fs->init->type == ASTNodeType::EXPR_STMT) {
                gen_expression(static_cast<ExprStmt*>(fs->init.get())->expr.get());
            } else {
                gen_statement(fs->init.get());
            }
        }
        out << "; ";
        if (fs->condition) gen_expression(fs->condition.get());
        out << "; ";
        if (fs->increment) gen_expression(fs->increment.get());
        out << ") {\n";
        indent_level++;
        gen_block_stmt(static_cast<BlockStmt*>(fs->body.get()));
        indent_level--;
        indent(); out << "}\n";
    }

    void gen_return_stmt(ReturnStmt* rs) {
        indent(); out << "return";
        if (rs->value) {
            out << " ";
            gen_expression(rs->value.get());
        }
        out << ";\n";
    }

    void gen_expression(ASTNode* node) {
        if (!node) return;

        switch (node->type) {
            case ASTNodeType::INT_LITERAL: {
                auto* il = static_cast<IntLiteral*>(node);
                if (!il->literal_type.empty()) {
                    out << "(" << map_type(il->literal_type) << ")";
                }
                out << il->value;
                break;
            }
            case ASTNodeType::FLOAT_LITERAL: {
                auto* fl = static_cast<FloatLiteral*>(node);
                if (!fl->literal_type.empty()) {
                    out << "(" << map_type(fl->literal_type) << ")";
                }
                out << fl->value;
                break;
            }
            case ASTNodeType::STRING_LITERAL: {
                auto& sv = static_cast<StringLiteral*>(node)->value;
                out << "((BrickString){.data=\"" << sv << "\", .len=(size_t)" << sv.size() << "})";
                break;
            }
            case ASTNodeType::BOOL_LITERAL:
                out << (static_cast<BoolLiteral*>(node)->value ? "1" : "0");
                break;
            case ASTNodeType::CHAR_LITERAL:
                out << "'" << static_cast<CharLiteral*>(node)->value << "'";
                break;
            case ASTNodeType::NULL_LITERAL:
                out << "NULL";
                break;
            case ASTNodeType::IDENT_EXPR: {
                auto* ident = static_cast<IdentExpr*>(node);
                if (!current_struct_name.empty() &&
                    current_struct_fields.count(ident->name)) {
                    out << "this->" << ident->name;
                } else {
                    out << ident->name;
                }
                break;
            }
            case ASTNodeType::BINARY_OP: {
                auto* bin = static_cast<BinaryOp*>(node);
                // [OPTIMIZATION] Constant folding: pre-compute constant expressions
                // If both operands are literals, compute at compile time
                auto* left = bin->left.get();
                auto* right = bin->right.get();
                if (left->type == ASTNodeType::INT_LITERAL &&
                    right->type == ASTNodeType::INT_LITERAL) {
                    auto* lil = static_cast<IntLiteral*>(left);
                    auto* ril = static_cast<IntLiteral*>(right);
                    int64_t result = 0;
                    bool can_fold = true;
                    switch (bin->op) {
                        case TokenType::PLUS:  result = lil->value + ril->value; break;
                        case TokenType::MINUS: result = lil->value - ril->value; break;
                        case TokenType::STAR:  result = lil->value * ril->value; break;
                        case TokenType::SLASH:
                            if (ril->value != 0) result = lil->value / ril->value;
                            else can_fold = false;
                            break;
                        default: can_fold = false; break;
                    }
                    if (can_fold) {
                        out << result;
                        break;
                    }
                }
                if (left->type == ASTNodeType::FLOAT_LITERAL &&
                    right->type == ASTNodeType::FLOAT_LITERAL) {
                    auto* lfl = static_cast<FloatLiteral*>(left);
                    auto* rfl = static_cast<FloatLiteral*>(right);
                    double result = 0;
                    bool can_fold = true;
                    switch (bin->op) {
                        case TokenType::PLUS:  result = lfl->value + rfl->value; break;
                        case TokenType::MINUS: result = lfl->value - rfl->value; break;
                        case TokenType::STAR:  result = lfl->value * rfl->value; break;
                        case TokenType::SLASH:
                            if (rfl->value != 0.0) result = lfl->value / rfl->value;
                            else can_fold = false;
                            break;
                        default: can_fold = false; break;
                    }
                    if (can_fold) {
                        out << result;
                        break;
                    }
                }
                out << "(";
                gen_expression(bin->left.get());
                out << " " << token_type_to_op(bin->op) << " ";
                gen_expression(bin->right.get());
                out << ")";
                break;
            }
            case ASTNodeType::UNARY_OP: {
                auto* un = static_cast<UnaryOp*>(node);
                out << token_type_to_op(un->op);
                gen_expression(un->operand.get());
                break;
            }
            case ASTNodeType::CALL_EXPR: {
                auto* call = static_cast<CallExpr*>(node);

                // Method call: obj.method(args)
                // Chamada de metodo: obj.method(args)
                if (call->callee->type == ASTNodeType::MEMBER_EXPR) {
                    auto* mem = static_cast<MemberExpr*>(call->callee.get());

                    // Handle block.reset() built-in
                    // Trata block.reset() embutido
                    if (mem->object->resolved_type == "block") {
                        if (mem->member == "reset") {
                            out << "block_reset(";
                            gen_expression(mem->object.get());
                            out << ")";
                            return;
                        }
                    }

                    {
                        std::string obj_type = mem->object->resolved_type;
                        std::string base_type = obj_type;
                        if (!base_type.empty() && base_type.back() == '*') base_type.pop_back();

                        if (struct_map.count(base_type)) {
                            out << mangle_name(base_type, mem->member) << "(";
                            gen_expression(mem->object.get());
                            for (size_t i = 0; i < call->arguments.size(); i++) {
                                out << ", ";
                                gen_expression(call->arguments[i].get());
                            }
                            out << ")";
                            return;
                        }
                    }

                    gen_expression(mem->object.get());
                    out << "." << mem->member << "(";
                    for (size_t i = 0; i < call->arguments.size(); i++) {
                        gen_expression(call->arguments[i].get());
                        if (i + 1 < call->arguments.size()) out << ", ";
                    }
                    out << ")";
                    break;
                }

                // Constructor call: StructName(args) - standalone (not assignment)
                // Chamada de construtor: StructName(args) - isolada (sem atribuicao)
                if (call->callee->type == ASTNodeType::IDENT_EXPR) {
                    auto* callee_ident = static_cast<IdentExpr*>(call->callee.get());

                    // print() built-in
                    // print() embutido
                    if (callee_ident->name == "print") {
                        gen_print_call(call);
                        break;
                    }

                    if (struct_map.count(callee_ident->name)) {
                        std::string struct_name = callee_ident->name;
                        out << mangle_name(struct_name, struct_name) << "(";
                        for (size_t i = 0; i < call->arguments.size(); i++) {
                            gen_expression(call->arguments[i].get());
                            if (i + 1 < call->arguments.size()) out << ", ";
                        }
                        out << ")";
                        break;
                    }

                    // error("msg") built-in
                    // error("msg") embutido
                    if (callee_ident->name == "error") {
                        out << "fprintf(stderr, ";
                        if (!call->arguments.empty()) {
                            gen_expression(call->arguments[0].get());
                        }
                        out << "); exit(1)";
                        break;
                    }

                    // Extern function call (with String→*u8 auto-conversion)
                    // Chamada de funcao externa (com conversao automatica String→*u8)
                    auto ext_it = extern_funcs.find(callee_ident->name);
                    if (ext_it != extern_funcs.end()) {
                        auto* ext_fd = ext_it->second;
                        out << ext_fd->name << "(";
                        for (size_t i = 0; i < call->arguments.size(); i++) {
                            if (i > 0) out << ", ";
                            auto* arg = call->arguments[i].get();
                            if (i < ext_fd->params.size()) {
                                auto* pd = static_cast<ParamDecl*>(ext_fd->params[i].get());
                                if (pd->type_name == "*u8" && arg->resolved_type == "String") {
                                    gen_expression(arg);
                                    out << ".data";
                                    continue;
                                }
                            }
                            gen_expression(arg);
                        }
                        out << ")";
                        break;
                    }
                }

                gen_expression(call->callee.get());
                out << "(";
                for (size_t i = 0; i < call->arguments.size(); i++) {
                    gen_expression(call->arguments[i].get());
                    if (i + 1 < call->arguments.size()) out << ", ";
                }
                out << ")";
                break;
            }
            case ASTNodeType::MEMBER_EXPR: {
                auto* mem = static_cast<MemberExpr*>(node);
                if (mem->object->type == ASTNodeType::IDENT_EXPR) {
                    auto* ident = static_cast<IdentExpr*>(mem->object.get());
                    if (pointer_vars.count(ident->name)) {
                        gen_expression(mem->object.get());
                        out << "->" << mem->member;
                        break;
                    }
                }
                gen_expression(mem->object.get());
                out << "." << mem->member;
                break;
            }
            case ASTNodeType::INDEX_EXPR: {
                auto* ie = static_cast<IndexExpr*>(node);
                gen_expression(ie->array.get());
                out << "[";
                gen_expression(ie->index.get());
                out << "]";
                break;
            }
            case ASTNodeType::ASSIGNMENT: {
                auto* assign = static_cast<Assignment*>(node);
                bool target_is_ptr = false;
                if (assign->target->type == ASTNodeType::IDENT_EXPR) {
                    auto* ident = static_cast<IdentExpr*>(assign->target.get());
                    target_is_ptr = pointer_vars.count(ident->name);
                }
                if (assign->op == TokenType::ASSIGN) {
                    if (target_is_ptr) out << "*";
                    gen_expression(assign->target.get());
                    out << " = ";
                    gen_expression(assign->value.get());
                } else {
                    if (target_is_ptr) {
                        out << "*";
                        gen_expression(assign->target.get());
                        out << " " << token_type_to_op(assign->op) << " ";
                        gen_expression(assign->value.get());
                    } else {
                        gen_expression(assign->target.get());
                        out << " " << token_type_to_op(assign->op) << " ";
                        gen_expression(assign->value.get());
                    }
                }
                break;
            }
            case ASTNodeType::ALLOC_INLINE: {
                auto* ai = static_cast<AllocInline*>(node);
                if (should_use_pool(ai->expr->resolved_type)) {
                    out << "(*pool_alloc(__pool_" << ai->block_name << ", sizeof(";
                } else {
                    out << "(*block_alloc(" << ai->block_name << ", sizeof(";
                }
                gen_expression(ai->expr.get());
                out << ")))";
                break;
            }
            case ASTNodeType::RESET_EXPR: {
                auto* re = static_cast<ResetExpr*>(node);
                out << "block_reset(" << re->block_name << ")";
                break;
            }
            default:
                out << "/* unsupported expression */";
                break;
        }
    }

    std::string map_type(const std::string& mc_type) {
        // Pointer type: *T -> mapped_base_type*
        // *u8 -> char* (C string convention, matches BrickString.data)
        if (!mc_type.empty() && mc_type[0] == '*') {
            std::string base = mc_type.substr(1);
            if (base == "u8" || base == "byte" || base == "char")
                return "char*";
            return map_type(base) + "*";
        }

        static const std::unordered_map<std::string, std::string> type_map = {
            {"int", "int32_t"},
            {"i32", "int32_t"},
            {"i64", "int64_t"},
            {"long", "int64_t"},
            {"i16", "int16_t"},
            {"short", "int16_t"},
            {"i8", "int8_t"},
            {"u8", "uint8_t"},
            {"byte", "uint8_t"},
            {"u16", "uint16_t"},
            {"u32", "uint32_t"},
            {"u64", "uint64_t"},
            {"float", "float"},
            {"f32", "float"},
            {"f64", "double"},
            {"bool", "uint8_t"},
            {"char", "uint8_t"},
            {"String", "BrickString"},
            {"void", "void"},
            {"block", "BlockCtx*"},
            {"usize", "size_t"},
            {"isize", "ptrdiff_t"},
        };

        auto it = type_map.find(mc_type);
        if (it != type_map.end()) return it->second;
        return mc_type;
    }

    std::string normalize_type_name(const std::string& t) {
        if (t == "byte" || t == "char") return "u8";
        if (t == "short") return "i16";
        if (t == "int") return "i32";
        if (t == "long") return "i64";
        if (t == "float") return "f32";
        if (t == "double") return "f64";
        return t;
    }

    bool is_integer_type(const std::string& t) {
        std::string n = normalize_type_name(t);
        return n == "u8" || n == "u16" || n == "u32" || n == "u64" ||
               n == "i8" || n == "i16" || n == "i32" || n == "i64" ||
               n == "usize" || n == "isize" || n == "bool";
    }

    bool is_float_type_name(const std::string& t) {
        std::string n = normalize_type_name(t);
        return n == "f32" || n == "f64";
    }

    void gen_print_call(CallExpr* call) {
        auto& args = call->arguments;

        // 0 arguments
        // 0 argumentos
        if (args.empty()) {
            out << "io_print_newline()";
            return;
        }

        auto* first = args[0].get();
        bool is_fmt = (first->type == ASTNodeType::STRING_LITERAL);

        // Check if string literal contains {N} placeholders
        // Verifica se literal de string contem placeholders {N}
        bool has_placeholders = false;
        if (is_fmt) {
            auto& sv = static_cast<StringLiteral*>(first)->value;
            has_placeholders = (sv.find('{') != std::string::npos);
        }

        // Single argument, no placeholders → direct io_print_X
        // Argumento unico, sem placeholders → io_print_X direto
        if (args.size() == 1 && !has_placeholders) {
            gen_print_single(first);
            return;
        }

        // Format string path: first arg is String literal with {N} or multiple args
        // Caminho de string formatada: primeiro arg e literal String com {N} ou args multiplos
        gen_printf_call(call);
    }

    void gen_print_single(ASTNode* arg) {
        std::string t = arg->resolved_type;
        std::string tn = normalize_type_name(t);
        if (t == "char") {
            out << "io_print_char(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "u8") {
            out << "io_print_u8(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "u16") {
            out << "io_print_u16(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "u32") {
            out << "io_print_u32(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "u64") {
            out << "io_print_u64(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "i8") {
            out << "io_print_i8(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "i16") {
            out << "io_print_i16(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "i32") {
            out << "io_print_i32(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "i64") {
            out << "io_print_i64(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "f32") {
            out << "io_print_f32(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "f64") {
            out << "io_print_f64(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "bool") {
            out << "io_print_bool(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "usize") {
            out << "io_print_usize(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "isize") {
            out << "io_print_isize(";
            gen_expression(arg);
            out << ")";
        } else if (tn == "String") {
            bool is_ptr = (arg->type == ASTNodeType::IDENT_EXPR) &&
                          pointer_vars.count(static_cast<IdentExpr*>(arg)->name);
            out << "io_print_string(";
            gen_expression(arg);
            out << (is_ptr ? "->data, " : ".data, ");
            gen_expression(arg);
            out << (is_ptr ? "->len)" : ".len)");
        } else {
            out << "/* print unsupported type */";
        }
    }

    void gen_printf_call(CallExpr* call) {
        auto& args = call->arguments;
        std::string fmt_str;
        if (args[0]->type == ASTNodeType::STRING_LITERAL) {
            fmt_str = static_cast<StringLiteral*>(args[0].get())->value;
        }

        // Build the printf format string
        // Constroi a string de formato printf
        std::string printf_fmt;
        std::vector<size_t> placeholder_indices; // which arg index each placeholder maps to
                                                 // indice do argumento que cada placeholder mapeia
        std::vector<std::string> arg_types; // for type mapping
                                            // para mapeamento de tipo

        size_t i = 0;
        while (i < fmt_str.size()) {
            if (fmt_str[i] == '{' && i + 1 < fmt_str.size()) {
                size_t end = fmt_str.find('}', i + 1);
                if (end != std::string::npos) {
                    std::string num = fmt_str.substr(i + 1, end - i - 1);
                    bool all_digits = !num.empty() && num.find_first_not_of("0123456789") == std::string::npos;
                    if (all_digits) {
                        int idx = std::stoi(num);
                        if (idx >= 0 && idx + 1 < (int)args.size()) {
                            auto* placeholder_arg = args[idx + 1].get();
                            std::string pt = placeholder_arg->resolved_type;
                            arg_types.push_back(pt);
                            placeholder_indices.push_back((size_t)idx + 1);
                            std::string ptn = normalize_type_name(pt);
                            if (pt == "char" || ptn == "u8") printf_fmt += "%" PRIu8;
                            else if (ptn == "u16") printf_fmt += "%" PRIu16;
                            else if (ptn == "u32") printf_fmt += "%" PRIu32;
                            else if (ptn == "u64") printf_fmt += "%" PRIu64;
                            else if (ptn == "i8") printf_fmt += "%" PRId8;
                            else if (ptn == "i16") printf_fmt += "%" PRId16;
                            else if (ptn == "i32") printf_fmt += "%" PRId32;
                            else if (ptn == "i64") printf_fmt += "%" PRId64;
                            else if (ptn == "usize") printf_fmt += "%zu";
                            else if (ptn == "isize") printf_fmt += "%td";
                            else if (is_float_type_name(pt)) printf_fmt += "%f";
                            else if (ptn == "String") printf_fmt += "%.*s";
                            else if (ptn == "bool") printf_fmt += "%s";
                            else printf_fmt += "%s";
                            i = end + 1;
                            continue;
                        }
                    }
                }
            }
            // Escape % for printf
            // Escapa % para printf
            if (fmt_str[i] == '%') printf_fmt += "%%";
            else printf_fmt += fmt_str[i];
            i++;
        }

        // Add newline at end if not already present
        // Adiciona newline no final se ja nao estiver presente
        if (printf_fmt.empty() || printf_fmt.back() != '\n') {
            printf_fmt += "\\n";
        }

        out << "io_printf(\"" << printf_fmt << "\"";

        // Generate arguments
        // Gera argumentos
        for (size_t ai = 0; ai < placeholder_indices.size(); ai++) {
            out << ", ";
            size_t arg_idx = placeholder_indices[ai];
            auto* arg = call->arguments[arg_idx].get();
            std::string pt = arg_types[ai];

            std::string ptn = normalize_type_name(pt);
            if (pt == "char" || (is_integer_type(pt) && ptn != "bool")) {
                gen_expression(arg);
            } else if (ptn == "String") {
                bool is_ptr = (arg->type == ASTNodeType::IDENT_EXPR) &&
                              pointer_vars.count(static_cast<IdentExpr*>(arg)->name);
                gen_expression(arg);
                out << (is_ptr ? "->len, " : ".len, ");
                gen_expression(arg);
                out << (is_ptr ? "->data" : ".data");
            } else if (ptn == "bool") {
                gen_expression(arg);
                out << " ? \"true\" : \"false\"";
            } else {
                gen_expression(arg);
            }
        }

        out << ")";
    }

    std::string token_type_to_op(TokenType type) {
        switch (type) {
            case TokenType::PLUS: return "+";
            case TokenType::MINUS: return "-";
            case TokenType::STAR: return "*";
            case TokenType::SLASH: return "/";
            case TokenType::EQ: return "==";
            case TokenType::NEQ: return "!=";
            case TokenType::LT: return "<";
            case TokenType::GT: return ">";
            case TokenType::LEQ: return "<=";
            case TokenType::GEQ: return ">=";
            case TokenType::AND: return "&&";
            case TokenType::OR: return "||";
            case TokenType::NOT: return "!";
            case TokenType::ASSIGN: return "=";
            case TokenType::PLUS_ASSIGN: return "+=";
            case TokenType::MINUS_ASSIGN: return "-=";
            case TokenType::STAR_ASSIGN: return "*=";
            case TokenType::SLASH_ASSIGN: return "/=";
            default: return "/*op*/";
        }
    }
};

CodegenResult generate_c(
    const std::vector<std::unique_ptr<ProgramNode>>& asts,
    const PackageTable& packages)
{
    Codegen codegen(packages);
    return codegen.generate(asts);
}

} // namespace brick
  // namespace brick
