# Build: brick_visualizer — ncurses memory visualizer
Import('env', 'has_visualizer')

if not has_visualizer:
    Return('lib_viz')

env_viz = env.Clone()
env_viz.ParseConfig('pkg-config --cflags --libs ncurses')

lib_viz = env_viz.Library('#build/brick_visualizer', ['memvis.cpp'])

Return('lib_viz')
